import { PaymentAdviceData } from "@/types";

export const defaultPaymentAdviceData: PaymentAdviceData = {
  date: "02/06/2026",
  goodsDescription: "Aluminum scrap Tense as per ISRI",
  customerName: "GIREXIM INTERNATIONAL PVT LTD",
  customerAddress: "502, BUSINESS SQUARE, NEAR ZANZARDA BYPASS CHOWKDI, ZANZARDA ROAD, JUNAGADH-362001",
  iec: "2416903306",
  inrAcNo: "99909879577688",
  fcyAcNo: "",
  amount: "64,265.57",
  amountWords: "USD SIXTY-FOUR THOUSAND TWO HUNDRED SIXTY-FIVE AND FIFTY-SEVEN CENTS ONLY",
  beneficiaryName: "GRAND TRADING L.L.C FZ",
  beneficiaryAddress: "MEYDAN GRANDSTAND 6TH FLOOR MEYDAN ROAD, NAD AL SHEBA, DUBAI, U.A.E.",
  beneficiaryAcNo: "3708498512402(USD)",
  beneficiaryBank: "EMIRATES ISLAMIC BANK P.J.S.C. DEIRA, DUBAI",
  ibanNo: "AE600340003708498512402(USD)",
  swiftCode: "MEBLAEADXXX",
  aba: "",
  routingNo: "",
  sortCode: "",
  expectedDispatchDate: "30.06.2026",
  shippingCompany: "",
  portOfDispatch: "APAPA, NIGERIA",
  destinationPort: "MUNDRA, INDIA",
  proformaInvNo: "GTL/GEI/006/26-27",
  proformaInvDate: "01/06/2026",
  proformaInvAmount: "USD 64,265.57",
  hsnCode: "76020010",
  countryOfOrigin: "NIGERIA",
  importLicenseDetails: "N.A.",
  specialRefNo: "N.A.",
  rateContract: "",
  paymentType: "advance",
  remittanceType: "swift",
  chargesAcType: "onus",
  fcyCharges: "onus",
  boeNo: "",
  boeDate: "",
  boeCcy: "",
  boeAmount: "",
  boeUtilized: "",
  fobValue: "",
  adCode: "",
  portCode: "",
  boeDeclaration: true,
  boeDirectDetails: false,
  ofacDeclaration: true,
  fatfDeclaration: false,
  eefcDeclaration: false,
  spfcDeclaration: false,
  partPayment: false,
  femaDeclaration: true,
  femaRestricted: false,
  notUnderInvestigation: true,
  docProformaInvoice: true,
  docPurchaseOrder: false,
  docTransport: false,
  docBoe: false,
  docFormA2: false,
  docDelayedPayment: false,
  docOriginalLicense: false,
  docBankGuarantee: false,
  docOther: false,
  docOtherText: "",
  partPaymentReason: "",
  billRefNo: "",
  partPaymentCcy: "",
  partPaymentAmount: "",
  companyName: "GIREXIM INTERNATIONAL PVT LTD",
  authorizedSignatory: "",
};
