import { PerformaInvoiceData } from "@/types";

export const defaultPerformaInvoiceData: PerformaInvoiceData = {
  seller: "GRAND TRADING L.L.C FZ",
  sellerAddress: "MEYDAN GRANDSTAND, 6TH FLOOR, MEYDAN ROAD, NAD AL SHEBA, DUBAI, U.A.E.",
  invoiceNo: "GTL/GEI/006/26-27",
  date: "01/06/2026",
  incoTerms: "CNF",
  buyer: "GIREXIM INTERNATIONAL PVT LTD",
  buyerAddress: "502, BUSINESS SQUARE, TAPOVAN, NEAR ZANZARDA CHOWKDI, ZANZARDA ROAD, JUNAGADH - 362001, INDIA",
  gstNo: "24AAMCG3269L1Z6",
  mo: "9978302386",
  email: "gireximinternationalpvtltd@gmail.com",
  countryOfOrigin: "NIGERIA",
  portOfLoading: "ANY PORT OF NIGERIA",
  portOfDischarge: "MUNDRA, INDIA",
  notifyParty: "",
  paymentTerms: "100% ADVANCE PAYMENT OR PARTIALLY PAYMENT ALLOWED",
  shippingTerms: "",
  blNo: "",
  sBillNo: "",
  markAndNo: "",
  noOfBags: "",
  descriptionOfGoods: "Aluminum Scrap Tense as per ISRI",
  hsnCode: "76020010",
  quantity: "27.5",
  rate: "2336.93",
  amount: "64,265.57",
  valueInWords: "USD SIXTY-FOUR THOUSAND TWO HUNDRED SIXTY-FIVE AND FIFTY-SEVEN CENTS ONLY",
  bankName: "GRAND TRADING L.L.C-FZ",
  bankBranch: "EMIRATES ISLAMIC BANK P.J.S.C., DEIRA, DUBAI",
  ibanNo: "AE600340003708498512402(USD)",
  accountNo: "3708498512402(USD)",
  swiftCode: "MEBLAEADXXX",
  declaration: "WE DECLARE THAT THIS INVOICE SHOWS THE ACTUAL PRICE OF GOODS DESCRIBED AND ALL THE PERTICULARS ARE TRUE AND CORRECT.",
  companyEmail: "grandbusiness2024@gmail.com",
  companyPhone: "+971 50 280 0736",
};
