import { TaxInvoiceData } from "@/types";

export const defaultTaxInvoiceData: TaxInvoiceData = {
  seller: "GIREXIM INTERNATIONAL PVT LTD",
  sellerAddress: "502, BUSINESS SQUARE, TAPOVAN, NEAR ZANZARDA BYPASS CHOWKDI, ZANZARDA ROAD, JUNAGADH - 362001",
  gstNo: "24AAMCG3269L1Z6",
  pan: "AAMCG3269L",
  invoiceNo: "GIREXP-T-01/26-27",
  date: new Date().toLocaleDateString("en-GB"),
  billTo: "DEVMETA INDUSTRIES LLP",
  billToAddress: "B-93 GIDC, ELECTRONIC ESTATE\nSECTOR NO -25, GANDHINAGAR",
  billToGst: "24AASFD6766A1ZC",
  billToPan: "AASFD6766A",
  shipTo: "DEVMETA INDUSTRIES LLP",
  shipToAddress: "GROUND FLOOR SUR NO.317,318 NEAR RANASAN GIDC CIRCLE SHREE PANCHSHIL EDUCATION TRUST PUNDHRA GANDHINAGAR GUJARAT - 382855",
  shipToGst: "24AASFD6766A1ZC",
  shipToPan: "AASFD6766A",
  material: "ALUMINIUM SCRAP",
  containerNo: "CAAU6529285",
  noOfCon: "1X40'",
  totalWeight: "27.499 MT",
  pol: "APAPA, NIGERIA",
  pod: "MUNDRA, GUJARAT",
  srNo: "1",
  hsnCode: "76020010",
  descriptionOfGoods: "Aluminium Scrap",
  qtyKg: "27,499",
  rateKg: "297",
  amount: "81,67,203.00",
  cgst: "7,35,048.27",
  sgst: "7,35,048.27",
  roundOff: "0.46",
  grandTotal: "96,37,300.00",
  amountInWords: "NINETY-SIX LAKE THIRTY-SEVEN THOUSAND THREE HUNDRED RUPEE ONLY",
  bankName: "GIREXIM INTERNATIONAL PVT LTD",
  bankBranchName: "HDFC BANK LTD",
  accountNo: "99909879577688",
  ifscCode: "HDFC0000231",
  swiftCodeTax: "HDFCINBBAHM",
  micrCode: "362240001",
  branch: "MOTIBAUG, JUNAGADH",
  terms: [
    "1) CUSTOM CLEARANCE TO BE DONE BY SELLER AT MUNDRA PORT",
    "2) NO CLAIM UPTO 2% FOR IRON ATTACHMENTS. ABOVE 2% ATTACHMENTS CLAIM WILL BE PAID BY SUPPLIER",
    "3) PAYMENT TERMS: 10% ADVANCE AGAINST PROFORMA INVOICE",
    "4) 85% PAYMENT TO BE MADE WHEN CONTAINER REACHES AT MUNDRA PORT",
    "5) REMAINING 5% OF PAYMENT WILL BE MADE WITHIN 10 DAYS AFTER DELIVERY OF THE GOODS",
    "6) TRANSPORT WILL BE PAID BY THE SUPPLIER FROM MUNDRA TO GANDHINAGAR",
  ],
};

export function getTaxInvoiceDefaults(): TaxInvoiceData {
  return { ...defaultTaxInvoiceData };
}
